### ISSUE TITLE
1.7.10-v2版本发送弹幕会发出两条

### ISSUE THREAD

**Issue by hammer354** [zlainsama/BilicraftComments#4]
服务端为KCauldron-1.7.10-1448.133，客户端Forge版本为10.13.4.1448-1.7.10，服务端和客户端的系统为Win 10，Win 7试过也有这个问题，服务端已安装这个Mod并安装了服务端插件，并在配置文件内关闭了白名单模式。具体现象为按下I键输入弹幕内容回车发送后，屏幕上出现两条弹幕，弹幕过后聊天栏里也出现两条聊天消息。

**Comment by zlainsama** [comment]
嗯，你需要只安装mod或者只安装服务端插件

**Comment by zlainsama** [comment]
1.7.10版本的那个服务端插件是一个完整功能的服务端，不过是插件版的，功能并不一致。所以你两个都装了之后就会得到两条信息。

**Comment by hammer354** [comment]
原来如此，那请问功能具体有什么不同呢？

**Comment by zlainsama** [comment]
具体差别我忘记了，只不过mod这边很多是通过修改设置来进行限制的，而插件那边我记得是通过赋予权限节点之类的。这次的插件并不是我制作的。

**Comment by zlainsama** [comment]
啊，在客户端使用上是不会有差别。

**Comment by hammer354** [comment]
好的，了解了，谢谢！
